project:
  type: website
  output-dir: ../docs
  resources:
    - "admin/**"
    - "tracker/_media/**"
    - "assets/amazon_rainforest.mp4"
    - "assets/projeto_bd.png"

website:
  title: "EcoHub"
  site-url: "https://anicolella.github.io/EcoHub/"
  favicon: assets/favicon.svg
  search: true
  repo-url: "https://github.com/anicolella/EcoHub"
  navbar:
    logo: assets/logo.svg
    left:
      - text: In√≠cio
        href: index.qmd
      - text: "Gest√£o"
        menu:
          - text: "Tracker"
            href: tracker.qmd
          - text: "Commits"
            href: '#'
          - text: "Wiki"
            href: '#'
      - text: Documenta√ß√£o
        href: documentacao.qmd
      - text: Equipe
        href: equipe.qmd
      - text: Sobre
        href: sobre.qmd
    tools:
      - icon: moon
        href: "javascript:void(0)"
        aria-label: "Toggle dark mode"
      - icon: github
        href: "https://github.com/anicolella/EcoHub"
        aria-label: "GitHub repository"
      - icon: envelope-at
        href: "mailto:contato@ecohub.com"
        aria-label: "Enviar e-mail"
      - text: "üñáÔ∏è"
        menu:
          - text: "üìö CURSOS"
            href: "#"
          - text: "- Curso A"
            href: "#"
          - text: "- Curso B"
            href: "#"
          - text: "- Curso C"
            href: "#"
          - text: "- Curso D"
            href: "#"
          - text: "üíª PACOTES"
            href: "#"
          - text: "- R"
            href: "#"
          - text: "- Python"
            href: "#"
          - text: "‚öíÔ∏è UTILIT√ÅRIOS"
            href: "#"
          - text: "- Site tal"
            href: "#"
          - text: "- Site tal"
            href: "#"
          - text: "- App tal"
            href: "#"
  page-footer:
    center: "¬© 2025 EcoHub"

format:
  html:
    theme: [default]                  
    css: assets/styles.css           
    toc: false
    smooth-scroll: true
    include-in-header: _includes/header.html
    include-before-body: _includes/drawer.html
    include-after-body: _includes/scripts.html
