project:
  type: website
  output-dir: ../docs
  resources:
    - "admin/**"
    - "tracker/_media/**"
    - "assets/amazon_rainforest.mp4"
    - "assets/wetlands.mp4"
    - "assets/projeto_bd.png"

website:
  title: "EcoHub"
  site-url: "https://anicolella.github.io/EcoHub/"
  favicon: assets/favicon.svg
  search: true
  repo-url: "https://github.com/anicolella/EcoHub"
  navbar:
    logo: assets/logo.svg
    left:
      - text: In√≠cio
        href: index.qmd
      - text: "Gest√£o"
        menu:
          - text: "Delibera√ß√µes"
            href: deliberacoes.qmd
          - text: "Commits"
            href: commits.qmd
      - text: Dados
        href: dados.qmd
      - text: Equipe
        href: equipe.qmd
      - text: Sobre
        href: sobre.qmd
    tools:
      - icon: moon
        href: "javascript:void(0)"
        aria-label: "Toggle dark mode"
      - icon: github
        href: "https://github.com/anicolella/EcoHub"
        aria-label: "GitHub repository"
      - icon: envelope-at
        href: "mailto:contato@ecohub.com"
        aria-label: "Enviar e-mail"
      - text: "Conte√∫do adicional"
        menu:

          - text: "üóÑÔ∏è BASES DE DADOS"           
            href: "#"
          - text: "Our Word in Data"
            href: "https://www.ourworldindata.org"
            target: "_blank"
          - text: "Brasil.gov"
            href: "https://data.un.org"
            target: "_blank"
          - text: "OCDE"
            href: "https://data.oecd.org"
            target: "_blank"
          - text: 'IBGE (Sidra)'
            href: "https://sidra.ibge.gov.br"
            target: "_blank"
          - text: "IpeaData"
            href: "https://www.ipeadata.gov.br"
            target: "_blank"

          - text: "üìö TREINAMENTOS"
            href: "#"
          - text: "Jurimetrics (Prof. Anicolella)"
            href: "https://anicolella.github.io/jurimetria/"
            target: "_blank"
          - text: "Introdu√ß√£o ao GIT e GitHub (a fazer)"
            href: "#"
            target: "_blank"
          - text: "An√°lise de dados com R (a fazer)"
            href: "#"
            target: "_blank"
          - text: "An√°lise de dados com Python (a fazer)"
            href: "#"
            target: "_blank"
          - text: "Latex para trabalhos acad√™micos (a fazer)"
            href: "#"
            target: "_blank"

  page-footer:
    center: "¬© 2025 EcoHub"

format:
  html:
    theme: [default]                  
    css: assets/styles.css           
    toc: false
    smooth-scroll: true
    include-in-header: _includes/header.html
    include-before-body: _includes/drawer.html
    include-after-body: _includes/scripts.html
