project: 
  type: website

website: 
  title: "análise descritiva RAMT provisória"
  navbar:
    left: 
      - principal.qmd

format: 
  html: 
    theme: journal
    code-fold: true
    code-summary: veja o código

mainfont: sans-serif;